services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cloudcare-postgres
    environment:
      POSTGRES_DB: cloudcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cloudcare_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cloudcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudcare_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: cloudcare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cloudcare-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass cloudcare_redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # CloudCare Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: cloudcare-backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudcare_db
      DB_USER: postgres
      DB_PASSWORD: cloudcare_dev_password
      DATABASE_URL: postgresql://postgres:cloudcare_dev_password@postgres:5432/cloudcare_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: cloudcare_redis_password
      WEARABLES_SERVICE_URL: http://wearables:6644
      WEARABLES_SERVICE_ENABLED: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - cloudcare-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      wearables-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); });"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Database migrations (run once)
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: cloudcare-migrations
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudcare_db
      DB_USER: postgres
      DB_PASSWORD: cloudcare_dev_password
      DATABASE_URL: postgresql://postgres:cloudcare_dev_password@postgres:5432/cloudcare_db
    networks:
      - cloudcare-network
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run db:migrate
    volumes:
      - ./database:/app/database

  # MongoDB for Wearables Service
  wearables-db:
    image: mongo:7-jammy
    container_name: cloudcare-wearables-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: iotopia
    ports:
      - "27017:27017"
    volumes:
      - wearables_mongo_data:/data/db
    networks:
      - cloudcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Wearables Service
  wearables:
    build:
      context: ./wearables
      dockerfile: Dockerfile
    container_name: cloudcare-wearables
    env_file:
      - ./wearables/.env
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 6644
      APP_DEBUG: "False"
      MONGO_URI: mongodb://root:iotopia@wearables-db:27017/hcgateway?authSource=admin
    ports:
      - "6644:6644"
    networks:
      - cloudcare-network
    depends_on:
      wearables-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./wearables/service-account.json:/app/service-account.json:ro

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  wearables_mongo_data:
    driver: local

networks:
  cloudcare-network:
    driver: bridge
